services:

  app:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    container_name: laravel_app
    working_dir: /var/www
    volumes:
      - ./backend:/var/www
    depends_on:
      - db
    networks:
      - app-network

  web:
    build:
      context: .
      dockerfile: docker/caddy/Dockerfile
    container_name: laravel_caddy
    env_file:
      - docker/caddy/.env
    ports:
      - "9023:9023"
      - "9023:9023/udp"
    dns:
      - 8.8.8.8
      - 1.1.1.1
    volumes:
      - ./backend:/var/www
      - ./docker/caddy/Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
    depends_on:
      - app
    networks:
      - app-network

  db:
    image: mysql:8
    container_name: laravel_db
    restart: always
    environment:
      MYSQL_DATABASE: laravel
      MYSQL_ROOT_PASSWORD: root
      MYSQL_PASSWORD: secret
      MYSQL_USER: laravel
    ports:
      - "3306:3306"
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - app-network

volumes:
  dbdata:
  caddy_data:
  caddy_config:

networks:
  app-network:
    driver: bridge
