services:
  caddy:
    container_name: caddy
    build:
      context: .
      dockerfile: ./docker/caddy/Dockerfile
    env_file:
      - ./docker/caddy/.env
    ports:
      - "9005:9005"
    volumes:
      - ./docker/caddy/Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
    depends_on:
      - web_server

  web_server:
    container_name: web_server
    build:
      context: .
      dockerfile: docker/web_server/Dockerfile
    volumes:
      - uploads:/uploads

  data_analyzer:
    container_name: data_analyzer
    build:
      context: .
      dockerfile: docker/data_analyzer/Dockerfile
    volumes:
      - uploads:/uploads

  mysql:
    image: mysql:8
    container_name: mysql
    environment:
      MYSQL_DATABASE: database
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_PASSWORD: admin
      MYSQL_USER: admin
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  caddy_data:
  caddy_config:
  mysql_data:
  uploads:
