services:
  caddy:
    build:
      context: .
      dockerfile: ./docker/caddy/Dockerfile
    env_file:
      - ./docker/caddy/.env
    ports:
      - "9027:9027"
    volumes:
      - ./docker/caddy/Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
    depends_on:
      - flask

  flask:
    build:
      context: .
      dockerfile: ./docker/flask/Dockerfile
    ports:
      - "5000:5000"

  mysql:
    image: mysql:8
    container_name: mysql
    environment:
      MYSQL_DATABASE: database
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_PASSWORD: admin
      MYSQL_USER: admin
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  caddy_data:
  caddy_config:
  mysql_data:
