name: Pylint

on:
  push:
  pull_request:

jobs:
  pylint-database-lib:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.14"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e src/database_lib
          pip install pylint

      - name: Analyze code with pylint
        run: |
          pylint \
            --rcfile src/database_lib/.pylintrc \
            src/database_lib/database_lib

  pylint-web-server:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.14"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install --no-cache-dir -r docker/web_server/requirements.txt
          pip install -e src/database_lib
          pip install pylint

      - name: Analyze code with pylint
        run: |
          pylint \
            --rcfile src/web_server/.pylintrc \
            src/web_server

  pylint-data-analyzer:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.14"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install --no-cache-dir -r docker/data_analyzer/requirements.txt
          pip install -e src/database_lib
          pip install pylint

      - name: Analyze code with pylint
        run: |
          pylint \
            --rcfile src/data_analyzer/.pylintrc \
            src/data_analyzer

  pylint-tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.14"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install --no-cache-dir -r docker/data_analyzer/requirements.txt
          pip install --no-cache-dir -r docker/web_server/requirements.txt
          pip install -e src/database_lib
          pip install pylint

      - name: Analyze code with pylint
        run: |
          pylint \
            --rcfile src/tests/.pylintrc \
            src/tests
